# More details of how to configure this file can be found in this link
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    target-branch: develop
    commit-message:
      prefix: "[dependabot]"
    assignees:
      - EladHeller
    reviewers:
      - EladHeller
    open-pull-requests-limit: 10 
    groups:
      typescript-eslint:
        applies-to: version-updates
        patterns:
          - "*typescript-eslint*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10 