env:
  browser: true
  es2021: true
globals:
  RequestCredentials: readonly
extends:
  - airbnb-base
  - plugin:import/typescript
  - plugin:jest/all
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  jest/prefer-expect-assertions: 0
  jest/no-hooks: 0
  jest/require-hook: 0
  no-console: off
  no-await-in-loop: off
  no-restricted-syntax: off
  import/extensions:
      ['error', 'ignorePackages', {'js': 'never', 'jsx': 'never', 'ts': 'never', 'tsx': 'never'}]
