env:
  node: true
  es2021: true
globals:
  RequestCredentials: readonly
extends:
  - airbnb-base
parserOptions: 
  ecmaVersion: 2023
  sourceType: module
rules:
  no-console: off
  no-await-in-loop: off
  no-restricted-syntax: off
  max-len: [error, { code: 120, ignoreStrings: true, ignoreTemplateLiterals: true, ignoreComments: true }]
  import/extensions:
      ['error', 'ignorePackages', {'js': 'never', 'jsx': 'never', 'ts': 'never', 'tsx': 'never'}]
