env:
  jest: true
extends:
  - plugin:import/typescript
  - plugin:jest/all
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.eslint.json'
plugins:
  - '@typescript-eslint'
rules:
  "@typescript-eslint/no-unused-vars": error
  import/no-extraneous-dependencies: off