import { JSDOM } from 'jsdom';
import fs from 'fs/promises';
// import WikiApi from '../../wiki/WikiApi';

const allLinks = [{ link: 'https://www.osimhistoria.com/osimpolitica/episode/867c3a62/', page: 'שיחה:הקפאת הבנייה ביהודה ושומרון' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep16', page: 'שיחה:דת ומדע' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep45', page: 'רומן שלוש הממלכות' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep73', page: 'שיחה:יום הכיפורים' },
  { link: 'https://www.osimhistoria.com/team', page: 'יובל דרור (סוציולוג)' },
  { link: 'https://www.osimhistoria.com/ibm', page: 'יובל דרור (סוציולוג)' },
  { link: 'https://www.osimhistoria.com/ibm', page: 'IBM' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep14', page: 'שיחה:דת ומדע' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep52', page: 'העיר המגודרת קאולון' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_322', page: 'עמי מויאל' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep332-telegraph-p1', page: 'שיחה:יומן קולנוע' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_178', page: 'סטקסנט' },
  //   { link: 'http://www.osimhistoria.com/', page: 'עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_193', page: 'כלי נגינה' },
  { link: 'https://www.osimhistoria.com/theanswer', page: 'דורון פישלר' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_190', page: 'תעופה' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_213', page: 'נמל' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_230/', page: 'עגבת' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_009', page: 'סטיב ווזניאק' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_326', page: 'פלוגת הטנקים הסודית בירושלים' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep329_jerusalem_tanks_pt2', page: 'פלוגת הטנקים הסודית בירושלים' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_082', page: 'כרונומטר' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_232', page: 'כדור פורח' },
  { link: 'https://www.osimhistoria.com/mir_space_station', page: 'שיחת תבנית:עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_131', page: 'שיחת תבנית:עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osimhistoria/', page: 'שיחת תבנית:עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_080', page: 'מדע בדיוני' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_201', page: 'קומראן' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_202', page: 'קומראן' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_244', page: 'קרב לטקיה' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_245', page: 'קרב לטקיה' },
  { link: 'https://www.osimhistoria.com/yl-pod/yl-pod_ep12', page: 'נישואים פתוחים' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_287', page: 'תמסח (דוברה)' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_288', page: 'תמסח (דוברה)' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_289', page: 'תמסח (דוברה)' },
  { link: 'https://www.osimhistoria.com/osim-politica', page: 'דפנה ליאל' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_196', page: 'גוטליב דיימלר' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_197', page: 'גוטליב דיימלר' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep336-keren-zarfati', page: 'סם פסיכדלי' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep334-transatlanticline-p1', page: 'חברת הטלגרף האטלנטי' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep334-transatlanticline-p1', page: 'טלגרף' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_100', page: 'פודקאסט' },
  { link: 'https://www.osimhistoria.com/osim-kotarot/ep96-spanish-flu', page: 'השפעת הספרדית' },
  { link: 'https://www.osimhistoria.com/osim-politica/osimpolitica_ep05', page: 'מרכז פוליטי בישראל' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_265', page: 'ג\'ורג\' מאלורי' },
  { link: 'https://www.osimhistoria.com/theanswer/ep62-king', page: 'מונרכיה' },
  { link: 'https://www.osimhistoria.com/theanswer/ep64-chizbat', page: 'אגם ניוס' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep16', page: 'נדודי בני ישראל במדבר' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep344-bernadout', page: 'פולקה ברנדוט' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_305', page: 'הנס ברגר (פסיכיאטר)' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_146', page: 'משחקי הכס (סדרת טלוויזיה)' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep110-shishak', page: 'רשימת ממצאים מרכזיים בארכאולוגיה מקראית' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_158', page: 'שיחה:SAT' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_146', page: 'משחקי הכס' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep345-nepoleon-p1', page: 'שיחת משתמש:Gilgamesh/ארכיון 76' },
  { link: 'https://www.osimhistoria.com/theanswer/ep65-wellerman', page: 'ולרמן' },
  { link: 'https://www.osimhistoria.com/osim-tech/ep93-serendipity', page: 'סרנדיפיות' },
  { link: 'https://www.osimhistoria.com/osim-tech/osim-tech-ep52', page: 'פרילנסר' },
  { link: 'https://www.osimhistoria.com/theanswer/ep68-soda', page: 'סודה לשתייה' },
  { link: 'https://www.osimhistoria.com//osimhistoria/oh_ep_212', page: 'אוניית מכולות' },
  { link: 'https://www.osimhistoria.com/yonatan-barak-pod', page: 'יונתן ברק' },
  { link: 'https://www.osimhistoria.com/hapoliticaim/ep01-avoda', page: 'מפלגת העבודה הישראלית' },
  { link: 'https://www.osimhistoria.com/hapoliticaim/ep02-havoda-p2', page: 'מפלגת העבודה הישראלית' },
  { link: 'https://www.osimhistoria.com/theanswer/ep73-the-kid-that-drew-cats', page: 'הילד שצייר חתולים' },
  { link: 'https://www.osimhistoria.com/police/police_ep02', page: 'הדס שפירא-מדמוני' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep121-hagar-and-yishmael/', page: 'ישמעאל' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep121-hagar-and-yishmael/', page: 'הגר' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep117-worship/', page: 'פולחן' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep113-babel/', page: 'מגדל בבל' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep112-hamachpela/', page: 'מערת המכפלה' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep103_yona/', page: 'ספר יונה' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep99/', page: 'עשרת השבטים' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep98/', page: 'דינה' },
  { link: 'https://www.osimhistoria.com/sheat-milhama/ep12-antebe', page: 'רון שכנר' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_300', page: 'עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_282', page: 'עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osim-tech/osim-tech-ep78', page: 'עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/sheat-milhama/ep13-masok', page: 'אבנר בלקנאי' },
  { link: 'https://www.osimhistoria.com/theanswer/ep76-einsteins-brain', page: 'המוח של אלברט איינשטיין' },
  { link: 'https://www.osimhistoria.com/theanswer', page: 'התשובה' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep03', page: 'פטמה' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep07', page: 'תנור מיקרוגל' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_327', page: 'פרוטו-אנושית' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep46', page: 'קונספירציית בילפלד' },
  { link: 'https://www.osimhistoria.com/osim-politica/osimpolitica_ep19', page: 'גל הגירת הפליטים לאירופה במאה ה-21' },
  { link: 'https://www.osimhistoria.com/theanswer/ep29-bazuka', page: 'מסטיק בזוקה' },
  { link: 'https://www.osimhistoria.com/police/police_ep01', page: 'אוטובוס האמהות' },
  { link: 'https://www.osimhistoria.com/med/med_ep29', page: 'משתמש:YoavR/ארגז חול 8' },
  { link: 'https://www.osimhistoria.com/med/med_ep30', page: 'משתמש:YoavR/ארגז חול 8' },
  { link: 'https://www.osimhistoria.com/%D7%94%D7%9E%D7%93%D7%A8%D7%99%D7%9A-%D7%9C%D7%A9%D7%93%D7%A8-%D7%94%D7%A4%D7%95%D7%93%D7%A7%D7%90%D7%A1%D7%98-%D7%94%D7%9E%D7%AA%D7%97%D7%99%D7%9C', page: 'עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_289', page: 'גשר הדוברות' },
  { link: 'https://www.osimhistoria.com/theanswer/ep64-chizbat', page: 'התפרצות מימית' },
  { link: 'https://www.osimhistoria.com/osim-politica/osimpolitica_ep14/', page: 'שחיתות שלטונית' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_291', page: 'אדם שימפנזה' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_293', page: 'אדם שימפנזה' },
  { link: 'https://www.osimhistoria.com/theanswer/ep72-europe', page: 'שיחה:אזרבייג\'ן' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep130-otiyot', page: 'דילוגי אותיות בתורה' },
  { link: 'https://www.osimhistoria.com/osim-tanach/', page: 'דילוגי אותיות בתורה' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_100/', page: 'פודקאסט' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep73', page: 'יום הכיפורים' },
  { link: 'https://www.osimhistoria.com/yl-pod', page: 'פאולה רוזנברג' },
  { link: 'https://www.osimhistoria.com/ima-aba/', page: 'יונתן ברק' },
  { link: 'https://www.osimhistoria.com/osim-politica/ep112-moshe-sharet', page: 'משה שרת' },
  { link: 'https://www.osimhistoria.com/osim-heshbon/ep47-reform-pension', page: 'אמיר ברנע' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep37', page: 'פרשת תמאם שוד' },
  { link: 'https://www.osimhistoria.com/osim-politica/ep102-bds', page: 'ויקיפדיה:הכה את המומחה/ארכיון309' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep137-job/', page: 'איוב' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep136-david-and-batsheba/', page: 'דוד ובת שבע' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep133-ehud-ben-gera/', page: 'אהוד בן גרא' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep125-tisha-beav/', page: 'תשעה באב' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep351-napoleon-part5/', page: 'אבן רוזטה' },
  { link: 'https://www.osimhistoria.com/hapoliticaim', page: 'רותם דנון' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_286', page: 'ריצ\'רד סטולמן' },
  { link: 'https://www.osimhistoria.com/police/ep08', page: 'מרד האסירים בכלא שטה' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep11', page: 'ויקיפדיה:הכה את המומחה/ארכיון310' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_312', page: 'יאן סלוט' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_314', page: 'יאן סלוט' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_041', page: 'נחיתת כלי תעופה חללי' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_053', page: 'אסון צ\'רנוביל' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep16', page: 'היסטוריה של עם ישראל' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep16', page: 'יציאת מצרים' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep60', page: 'יציאת מצרים' },
  { link: 'https://www.osimhistoria.com/osim-tanach', page: 'יציאת מצרים' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep61', page: 'יציאת מצרים' },
  { link: 'https://www.osimhistoria.com/healthy-and-happy', page: 'פאולה רוזנברג' },
  { link: 'https://www.osimhistoria.com/yl-pod', page: 'ליאון רוזנברג' },
  { link: 'https://www.osimhistoria.com/law', page: 'אטילה שומפלבי' },
  { link: 'https://www.osimhistoria.com/masa', page: 'אטילה שומפלבי' },
  { link: 'https://www.osimhistoria.com/kablanim', page: 'אטילה שומפלבי' },
  { link: 'https://www.osimhistoria.com/osim-heshbon', page: 'אטילה שומפלבי' },
  { link: 'https://www.osimhistoria.com/osim-heshbon', page: 'עומר מואב' },
  { link: 'https://www.osimhistoria.com/sheat-milhama', page: 'שלמה רז' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_201', page: 'צדוקים' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_202', page: 'צדוקים' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep145-red-sea', page: 'קריעת ים סוף' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_100', page: 'RSS' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep37', page: 'היסטוריה של עם ישראל' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep45', page: 'אחאב' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep49', page: 'תקופת האבות' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep48', page: 'ארכאולוגיה מקראית' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep52', page: 'אדם וחוה' },
  { link: 'https://www.osimhistoria.com/osim-tanach', page: 'אדם וחוה' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep53', page: 'מיכל' },
  { link: 'https://www.osimhistoria.com/osim-tanach', page: 'מיכל' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep54', page: 'דלילה' },
  { link: 'https://www.osimhistoria.com/osim-tanach', page: 'דלילה' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep58', page: 'כיבוש ירושלים בידי דוד' },
  { link: 'https://www.osimhistoria.com/osim-tanach', page: 'כיבוש ירושלים בידי דוד' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep62', page: 'עיר דוד' },
  { link: 'https://www.osimhistoria.com/osim-tanach', page: 'עיר דוד' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep64', page: 'מגילת רות' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep65', page: 'ביקורת נוסח המקרא' },
  { link: 'https://www.osimhistoria.com/osim-tanach', page: 'ביקורת נוסח המקרא' },
  { link: 'https://www.osimhistoria.com/grush/ep62-visut', page: 'ויסות שערי ניירות הערך קודם למשבר מניות הבנקים בישראל' },
  { link: 'https://www.osimhistoria.com/grush/ep62-visut', page: 'משבר מניות הבנקים' },
  { link: 'https://www.osimhistoria.com/grush/ep40-monopolies', page: 'כלכלת ארצות הברית' },
  { link: 'https://www.osimhistoria.com/grush/ep37-vanderbilt', page: 'כלכלת ארצות הברית' },
  { link: 'https://www.osimhistoria.com/grush/ep41-first-billionaire', page: 'כלכלת ארצות הברית' },
  { link: 'https://www.osimhistoria.com/grush/ep53-china', page: 'דנג שיאופינג' },
  { link: 'https://www.osimhistoria.com/grush/ep54-china-p2', page: 'דנג שיאופינג' },
  { link: 'https://www.osimhistoria.com/grush/ep55-china-hunger', page: 'דנג שיאופינג' },
  { link: 'https://www.osimhistoria.com/grush/ep56-sweat-shop', page: 'דנג שיאופינג' },
  { link: 'https://www.osimhistoria.com/grush/grush_ep01', page: 'הקפיצה הגדולה קדימה' },
  { link: 'https://www.osimhistoria.com/theanswer/ep111-names-part2', page: 'אוחזת ענף עץ השקד' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep150-rahav/', page: 'רחב' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep141-gideon/', page: 'גדעון בן יואש' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_157', page: 'מבצע גוזל' },
  { link: 'https://www.osimhistoria.com/theanswer/ep115-tamam-shud', page: 'פרשת תמאם שוד' },
  { link: 'https://www.osimhistoria.com/ben-shel-bat-shel/ep12-ayelet', page: 'איילת פריש' },
  { link: 'https://www.osimhistoria.com/theanswer/ep116-pope', page: 'סלסטינוס החמישי' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_282', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osim-tech/osim-tech-ep78', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osimhistoria', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/theanswer', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osim-tanach', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/med', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osim-politica', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osim-tech', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/software', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/yl-pod', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osim-heshbon', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/grush', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/sheat-milhama', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/yonatan-barak-pod', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/hapoliticaim', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/dabri-al-ze', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/hakipod', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osim-psychology', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/ima-aba', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/ima-aba/', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/law', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/healthy-and-happy', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/space', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osimbardak', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/ibm', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep46', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/kneged', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osim-tech/ep110-oxi', page: 'פרדו פארמה' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep335-transatlantic-line-p2', page: 'חברת הטלגרף האטלנטי' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep153-jews-are-coming', page: 'שיחה:דמות מקראית' },
  { link: 'https://www.osimhistoria.com/tanach-holidays-playlist', page: 'שיחה:דמות מקראית' },
  { link: 'https://www.osimhistoria.com/osim-politica/osimpolitica_ep14/', page: 'שחיתות שלטונית בישראל' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep129-isaac-p2', page: 'יצחק' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_041', page: 'שיחה:נחיתת כלי תעופה חללי' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep16', page: 'שיחה:יציאת מצרים' },
  { link: 'https://www.osimhistoria.com/osim-tech/osim-tech-ep81', page: 'אמזון' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep345-nepoleon-p1', page: 'היסטוריה של אלכסנדריה' },
  { link: 'https://www.osimhistoria.com/osim-politica/ep87-abbas', page: 'הרשימה הערבית המאוחדת' },
  { link: 'https://www.osimhistoria.com/osim-psychology/ep16-ocd', page: 'הפרעה טורדנית-כפייתית' },
  { link: 'https://www.osimhistoria.com/software/osim-tochna-38', page: 'מיקרו פרונטאנד' },
  { link: 'https://www.osimhistoria.com/theanswer/ep58-ketshup', page: 'קטשופ' },
  { link: 'https://www.osimhistoria.com/osim-minhar/', page: 'ערן מינהר' },
  { link: 'https://www.osimhistoria.com/osim-minhar/', page: 'רשת עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep162-isaac', page: 'עקדת יצחק' },
  { link: 'https://www.osimhistoria.com/law/ep18-piska', page: 'פסקת התגברות' },
  { link: 'https://www.osimhistoria.com/hakipod/ep27-karin-sandel', page: 'קארין סנדל' },
  { link: 'https://www.osimhistoria.com/intel', page: 'יובל דרור (סוציולוג)' },
  { link: 'https://www.osimhistoria.com/deloitte', page: 'יובל דרור (סוציולוג)' },
  { link: 'https://www.osimhistoria.com/theanswer/ep126-lambada', page: 'למבדה (שיר)' },
  { link: 'https://www.osimhistoria.com/theanswer/ep113-grandma-wheels', page: 'זחלגלגל' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep14', page: 'ויקיפדיה:הכה את המומחה/ארכיון319' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep166-israel-part2', page: 'מלכי ישראל ויהודה' },
  { link: 'https://www.osimhistoria.com/grush/ep26-tzena', page: 'מדיניות הקיצוב' },
  { link: 'https://www.osimhistoria.com/grush/ep29-tzena-final', page: 'מדיניות הקיצוב' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep169-david-jonatan/', page: 'יהונתן' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep163-10-commandments/', page: 'עשרת הדיברות' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep28', page: 'משולש ברמודה' },
  { link: 'https://www.osimhistoria.com/sheat-milhama/ep47-brown-blue', page: 'מבצע כחול וחום' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep07-american-way', page: 'מרגרט ברק-וייט' },
  { link: 'https://www.osimhistoria.com/law/ep14-virtual-rape', page: 'אונס וירטואלי' },
  { link: 'https://www.osimhistoria.com/theanswer/ep132-the-mystery-of-edwi--drood-', page: 'תעלומת אדווין דרוד' },
  { link: 'https://www.osimhistoria.com/theanswer/ep133-the-mystery-of-edwi--drood_pt.2-', page: 'תעלומת אדווין דרוד' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_017', page: 'חוצנים' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep177-bible/', page: 'קאנוניזציה של כתבים' },
  { link: 'https://www.osimhistoria.com/grush/ep73-pension', page: 'משבר קרנות הפנסיה הגרעוניות' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep39', page: 'נאורו' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep40', page: 'נאורו' },
  { link: 'https://www.osimhistoria.com/software/ep125-turing', page: 'מבחן טיורינג' },
  { link: 'https://www.osimhistoria.com/software/', page: 'מבחן טיורינג' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep180-yeravam_ben_navat/', page: 'ירבעם בן נבט' },
  { link: 'https://www.osimhistoria.com/theanswer/ep135-animals--', page: 'ויקיפדיה:הידעת?/מאפריל 2023' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep98/', page: 'מעשה שכם ודינה' },
  { link: 'https://www.osimhistoria.com/theanswer/ep74-666', page: '666 (מספר)' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep177-bible', page: 'תנ"ך' },
  { link: 'https://www.osimhistoria.com/theanswer/ep137-gargamel-', page: 'גרגמל (דמות)' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep182-yeravam_2.0', page: 'ירבעם השני' },
  { link: 'https://www.osimhistoria.com/theanswer/ep140-tomato-', page: 'פסק דין ניקס נגד הידן' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep41', page: 'עתליה' },
  { link: 'https://www.osimhistoria.com/osim-politica/ep156-svirut', page: 'עילת הסבירות' },
  { link: 'https://www.osimhistoria.com/sheat-milhama/ep19-1974', page: 'עדי אדירי' },
  { link: 'https://www.osimhistoria.com/osim-psychology/ep39--how_to_save_a_life', page: 'יוסי לוי בלז' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep177-bible', page: 'ההיסטוריות של התנ"ך' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep04', page: 'יום ה-H (שוודיה)' },
  { link: 'https://www.osimhistoria.com/osim-politica/osimpolitica_ep01', page: 'סתיו שפיר' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep41', page: 'יהואש (מלך יהודה)' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep41', page: 'המלכת יהואש' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep41', page: 'יהוידע הכהן' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep391-eretz-israel-ads', page: 'משרד פרסום' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep187-yosef_righteous/', page: 'יוסף' },
  { link: 'https://www.osimhistoria.com/osim-psychology/ep52-emotional_regulation', page: 'ויסות רגשי' },
  { link: 'https://www.osimhistoria.com/theanswer/ep74-666', page: 'החיה' },
  { link: 'https://www.osimhistoria.com/theanswer/ep147--dogs', page: 'שיחת משתמשת:Estyxxxx/שנת 2023' },
  { link: 'https://www.osimhistoria.com/sheat-milhama/ep16-bric', page: 'שיחת תבנית:עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep01-hague', page: 'אריך סלומון' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'אריך סלומון' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep02-staged-death', page: 'רוברט קאפה' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'רוברט קאפה' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep02-staged-death', page: 'מותו של חייל לויאליסט' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'מותו של חייל לויאליסט' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep03-rock30', page: 'מרכז רוקפלר' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep03-rock30', page: 'ג\'ון ד. רוקפלר, הבן' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'ג\'ון ד. רוקפלר, הבן' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep04-hindenburg', page: 'הינדנבורג (ספינת אוויר)' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'הינדנבורג (ספינת אוויר)' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep04-hindenburg', page: 'ספינת אוויר' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'ספינת אוויר' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep05-nguyen-van-lem', page: 'אדי אדמס' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'אדי אדמס' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep08-woodstock', page: 'פסטיבל וודסטוק' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'פסטיבל וודסטוק' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep09-the_decisive_moment', page: 'אנרי קרטייה ברסון' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'אנרי קרטייה ברסון' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep11-scourged_back', page: 'גורדון (עבד)' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'גורדון (עבד)' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep12-friends', page: 'לורל והארדי' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'לורל והארדי' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep12-friends', page: 'סטן לורל' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'סטן לורל' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep12-friends', page: 'אוליבר הארדי' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'אוליבר הארדי' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep14-daddy_wait', page: 'אבא, חכה לי' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'אבא, חכה לי' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep15-apollo8_nasa', page: 'זריחת הארץ' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'זריחת הארץ' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep15-apollo8_nasa', page: 'ויליאם אנדרס' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'ויליאם אנדרס' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep15-apollo8_nasa', page: 'אפולו 8' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'אפולו 8' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep16-ribbon', page: 'ג\'יימס קלרק מקסוול' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'ג\'יימס קלרק מקסוול' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep17-selfie', page: 'סלפי' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'סלפי' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep127-sea', page: 'קריעת ים סוף' },
  { link: 'https://www.osimhistoria.com/osim-heshbon/ep26-godesh', page: 'עומר מואב' },
  { link: 'https://www.osimhistoria.com/osim-kotarot/ep105-hague', page: 'שיחה:מתן גוטמן' },
  { link: 'https://www.osimhistoria.com/law', page: 'משתמש:BenG1/מתן גוטמן' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_164', page: 'ויקיפדיה:בוט/בדיקת הפרת זכויות יוצרים/ארכיון פברואר 2024' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep35', page: 'מיקולאיוס קונסטנטינס צ\'יורליוניס' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_286', page: 'משתמש:Cohzach2.0/טיוטה' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_286', page: 'מידע רוצה להיות חופשי' },
  { link: 'https://www.osimhistoria.com/sheat-milhama/ep69', page: 'אלון שוסטר' },
  { link: 'https://www.osimhistoria.com/sheat-milhama/ep69', page: 'קרב מפלסים' },
  { link: 'https://www.osimhistoria.com/theanswer/ep154_wiki', page: 'ויקיפדיה:אמינות' },
  { link: 'https://www.osimhistoria.com/theanswer/ep154_wiki', page: 'שיחת משתמש:מקף' },
  { link: 'https://www.osimhistoria.com/theanswer/ep154_wiki', page: 'ויקיפדיה:פרסומים בתקשורת' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep31', page: 'מציאת ספר התורה בימי יאשיהו' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep33', page: 'מציאת ספר התורה בימי יאשיהו' },
  { link: 'https://www.osimhistoria.com/theanswer/ep154_wiki', page: 'משתמש:מקף' },
  { link: 'https://www.osimhistoria.com/theanswer/ep155_encyclopedia', page: 'משתמש:מקף' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep46', page: 'רשומה בדויה' },
  { link: 'https://www.osimhistoria.com/theanswer/ep156_dinosaurs', page: 'דינוזאורים' },
  { link: 'https://www.osimhistoria.com/theanswer/ep155_encyclopedia', page: 'ויקיפדיה:כיכר העיר/ארכיון 176' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_125', page: 'ביגוד ומגדר' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep203-jacob_ladder', page: 'חלום יעקב' },
  { link: 'https://www.osimhistoria.com/theanswer/ep157_hebrew', page: 'האקדמיה ללשון העברית' },
  { link: 'https://www.osimhistoria.com/theanswer/ep155_encyclopedia', page: 'האנציקלופדיה העברית' },
  { link: 'https://www.osimhistoria.com/med/ep171-kik', page: 'גאורגי מרקוב' },
  { link: 'https://www.osimhistoria.com/med/ep171-kik', page: 'ריצין' },
  { link: 'https://www.osimhistoria.com/osim-kotarot/osimkotarot_ep16', page: 'רז צימט' },
  { link: 'https://www.osimhistoria.com/theanswer/ep77-europeans', page: 'רובים, חיידקים ופלדה' },
  { link: 'https://www.osimhistoria.com/theanswer/ep110-baby-shark', page: 'Baby Shark' },
  { link: 'https://www.osimhistoria.com/osimhistoria', page: 'עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep206-haazinu', page: 'פרשת האזינו' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep206-haazinu', page: 'שירת האזינו' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep47%7C', page: 'שיחה:נשים בתנ"ך' },
  { link: 'https://www.osimhistoria.com/bikoret', page: 'אור בוטבול' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep198-sne', page: 'הסנה הבוער' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep08-woodstock', page: 'The Woodstock Experience' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'The Woodstock Experience' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep18-servivor', page: 'אדה בלאקג\'ק' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'אדה בלאקג\'ק' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep19-servivor', page: 'Windows XP' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'Windows XP' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep20-gothic', page: 'גרנט ווד' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'גרנט ווד' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep20-gothic', page: 'גורדון פארקס' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'גורדון פארקס' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep21--mount_washington', page: 'הר וושינגטון' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'הר וושינגטון' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep22--lydia', page: 'לידיה ליטביאק' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'לידיה ליטביאק' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep23-pope', page: 'מהמט אלי אג\'ה' },
  { link: 'https://www.osimhistoria.com/osim-minhar', page: 'מהמט אלי אג\'ה' },
  { link: 'https://www.osimhistoria.com/theanswer/ep140-tomato-', page: 'התשובה' },
  { link: 'https://www.osimhistoria.com/theanswer/ep160_boring', page: 'התשובה' },
  { link: 'https://www.osimhistoria.com/theanswer/ep154_wiki', page: 'שיחה:תרמית אלן מקמסטרס' },
  { link: 'https://www.osimhistoria.com/osim-tech/osim-tech-ep09', page: 'שיחה:קמפוס IL' },
  { link: 'https://www.osimhistoria.com/theanswer/episode/78ff9d17/', page: 'שיחה:תרנגול הודו' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep48', page: 'תרנגול הודו' },
  { link: 'https://www.osimhistoria.com/theanswer/ep80-bazooka-correction', page: 'מסטיק בזוקה' },
  { link: 'https://www.osimhistoria.com/osim-politica', page: 'שלמה רז' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep213-world_creation', page: 'בריאת העולם בתנ"ך' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_300', page: 'ניקולה טסלה' },
  { link: 'https://www.osimhistoria.com/theanswer/ep99-columbus-rerun', page: 'כריסטופר קולומבוס' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep24', page: 'בריאת העולם בתנ"ך' },
  { link: 'https://www.osimhistoria.com/osim-tanach/osimtanach_ep25', page: 'בריאת העולם בתנ"ך' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep214-world_creation-b', page: 'בריאת העולם בתנ"ך' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_145', page: 'תרבות החירשים' },
  { link: 'https://www.osimhistoria.com/theanswer/ep164_1889', page: 'נלי בליי' },
  { link: 'https://www.osimhistoria.com/theanswer/ep164_1889', page: 'מסביב לעולם בשבעים ושניים יום' },
  { link: 'https://www.osimhistoria.com/theanswer/ep165', page: 'מסביב לעולם בשבעים ושניים יום' },
  { link: 'https://www.osimhistoria.com/theanswer/ep165', page: 'נלי בליי' },
  { link: 'https://www.osimhistoria.com/theanswer/ep144--little_hershel', page: 'יונתן הקטן' },
  { link: 'https://www.osimhistoria.com/theanswer/ep82-even-niyar', page: 'אבן נייר ומספריים' },
  { link: 'https://www.osimhistoria.com/theanswer/ep87-meter', page: 'מטר' },
  { link: 'https://www.osimhistoria.com/finklestein', page: 'ויקיפדיה:כיכר העיר/ארכיון 183' },
  { link: 'https://www.osimhistoria.com/ben-shel-bat-shel', page: 'אלון פוטרמן' },
  { link: 'https://www.osimhistoria.com/osim-minhar/ep55', page: 'מרי סלסט' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep139-pesher-habakuk', page: 'פשר חבקוק' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep220', page: 'תל מגידו' },
  { link: 'https://www.osimhistoria.com/grush/ep30-ponzi', page: 'צ\'ארלס פונזי' },
  { link: 'https://www.osimhistoria.com/theanswer', page: 'טיוטה:המובן מאליו' },
  { link: 'https://www.osimhistoria.com/sportcast/ep22-moran-samuel', page: 'מורן סמואל' },
  { link: 'https://www.osimhistoria.com/osim-tech/ep203_i_dont_know', page: 'הזיה (בינה מלאכותית)' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_186', page: 'סוני תאגיד אמריקה נגד אולפני יוניברסל סיטי בע"מ' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_056', page: 'ענקיות מעמקים' },
  { link: 'https://www.osimhistoria.com/osim-tech', page: 'שיחה:שיטיפיקציה' },
  { link: 'https://www.osimhistoria.com/grush/ep75-ata-part1?', page: 'אתא' },
  { link: 'https://www.osimhistoria.com/theanswer/ep86-what-is-the-shape-of-the-world-rerun', page: 'צבים כל הדרך למטה' },
  { link: 'https://www.osimhistoria.com/theanswer/ep151--unicorn', page: 'חד-קרן' },
  { link: 'https://www.osimhistoria.com/theanswer/ep152--unicorn_02', page: 'חד-קרן' },
  { link: 'https://www.osimhistoria.com/theanswer/ep153-2023', page: 'התשובה' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep43', page: 'התשובה' },
  { link: 'https://www.osimhistoria.com/theanswer/ep172', page: 'מעוף הדרקונים' },
  { link: 'https://www.osimhistoria.com/theanswer/ep154_wiki', page: 'שיחת תבנית:קישור לפודקאסט' },
  { link: 'https://www.osimhistoria.com/theanswer/ep112-chevalier', page: 'שבלייה ד\'איאון' },
  { link: 'https://www.osimhistoria.com/osim-asakim/ep04-david-avner', page: 'דוד אבנר' },
  { link: 'https://www.osimhistoria.com/ima-aba/ep04-bat-el-belan', page: 'בת אל בלן' },
  { link: 'https://www.osimhistoria.com/bikoret', page: 'משתמש:תומס קאמי/טיוטה:עמרי הכהן' },
  { link: 'https://www.osimhistoria.com/team', page: 'משתמש:תומס קאמי/טיוטה:עמרי הכהן' },
  { link: 'https://www.osimhistoria.com/theanswer/ep123-olympics', page: 'ויקיפדיה:הידעת?/המתנה' },
  { link: 'https://www.osimhistoria.com/yonatan-barak-pod/ep18-lefties', page: 'אמבידקסטריות' },
  { link: 'https://www.osimhistoria.com/theanswer/ep74-666', page: 'שיחת תבנית:פרופילי אנציקלופדיות/הטמעה/דוגמאות3' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_245', page: 'אריה מרמרי' },
  { link: 'https://www.osimhistoria.com/theanswer/ep102-around-the-world', page: 'פרדיננד מגלן' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep_447', page: 'ורנר פון בראון' },
  { link: 'https://www.osimhistoria.com/osim-tech/osim-tech-ep09', page: 'קמפוס IL' },
  { link: 'https://www.osimhistoria.com/theanswer/ep154_wiki', page: 'תרמית אלן מקמסטרס' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep329_jerusalem_tanks_pt2', page: 'רפאל ישעיה' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep114-shiloh', page: 'שילה (יישוב מקראי)' },
  { link: 'https://www.osimhistoria.com/theanswer/ep54-captain-drake-p2', page: 'אוסקר הרצל' },
  { link: 'https://www.osimhistoria.com/theanswer/ep_53', page: 'אוסקר הרצל' },
  { link: 'https://www.osimhistoria.com/theanswer/ep139-hanging_building-', page: 'שיחה:המשבר ההנדסי במרכז סיטיקורפ' },
  { link: 'https://www.osimhistoria.com/theanswer/ep154_wiki', page: 'דורון פישלר' },
  { link: 'https://www.osimhistoria.com/theanswer/ep106-quantum', page: 'מחשב קוונטי' },
  { link: 'https://www.osimhistoria.com/osim-tech/ep236', page: 'ויקיפדיה:כיכר העיר/ארכיון 188' },
  { link: 'https://www.osimhistoria.com/theanswer/ep183', page: 'צירוף מקרים' },
  { link: 'https://www.osimhistoria.com/theanswer/ep99-columbus-rerun', page: 'שיחה:עמוד ראשי' },
  { link: 'https://www.osimhistoria.com/osim-heshbon/ep70-discrimination', page: 'יונה רובינשטיין' },
  { link: 'https://www.osimhistoria.com/theanswer/ep177', page: 'רפואה אבולוציונית' },
  { link: 'https://www.osimhistoria.com/theanswer/ep154_wiki', page: 'משתמש:פרוגנתודון/מש:פרוגנתודון/רשימת תחזוקה לשמות/חסרי חוליות' },
  { link: 'https://www.osimhistoria.com/theanswer/ep171', page: 'שרקן' },
  { link: 'https://www.osimhistoria.com/yl-pod/ep83-surrogate-rerun', page: 'רונית אלוני' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_157', page: 'טייסת 106' },
  { link: 'https://www.osimhistoria.com/osimhistoria/oh_ep_233/', page: 'חליפת חלל' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep24', page: 'פופקורן' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep368-hatasha-part2', page: 'מלחמת ההתשה' },
  { link: 'https://www.osimhistoria.com/osimhistoria/ep_440', page: 'ניקלודיאון' },
  { link: 'https://www.osimhistoria.com/theanswer/ep189', page: 'גבי ודבי' },
  { link: 'https://www.osimhistoria.com/osim-kotarot/osimkotarot_ep05', page: 'עמיחי אתאלי' },
  { link: 'https://www.osimhistoria.com/grush/ep25-geoecon', page: 'גאוכלכלה' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep34', page: 'ויקיפדיה:כיכר העיר/ארכיון 189' },
  { link: 'https://osimhistoria.com/', page: 'ויקיפדיה:כיכר העיר' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep45', page: 'ויקיפדיה:כיכר העיר' },
  { link: 'https://osimhistoria.com/', page: 'תבנית:עושים היסטוריה' },
  { link: 'https://www.osimhistoria.com/theanswer/hatshuva_ep45', page: 'שיחת תבנית:עושים היסטוריה' },
  { link: 'https://osimhistoria.com/podcast/%D7%94%D7%AA%D7%A9%D7%95%D7%91%D7%94-%D7%A7%D7%A8%D7%91-%D7%9E%D7%95%D7%97%D7%95%D7%AA-%D7%A1%D7%99%D7%A4%D7%95%D7%A8%D7%99%D7%9D-%D7%9E%D7%A9%D7%9C%D7%95%D7%A9-%D7%94%D7%9E%D7%9E%D7%9C%D7%9B%D7%95/', page: 'שיחת תבנית:עושים היסטוריה' },
  { link: 'https://osimhistoria.com/podcast/395', page: 'תבנית:עושים היסטוריה1' },
  { link: 'https://osimhistoria.com/podcast/%D7%94%D7%9C%D7%94%D7%99%D7%98-%D7%94%D7%A6%D7%A8%D7%A4%D7%AA%D7%99-%D7%A9%D7%98%D7%9C%D7%98%D7%9C-%D7%90%D7%AA-%D7%AA%D7%A2%D7%A9%D7%99%D7%99%D7%AA-%D7%94%D7%92%D7%99%D7%99%D7%9E%D7%99%D7%A0%D7%92', page: 'תבנית:עושים היסטוריה1' },
  { link: 'https://osimhistoria.com/podcast/', page: 'תבנית:עושים היסטוריה1' },
  { link: 'https://osimhistoria.com/podcast/%D7%9C%D7%9E%D7%94-%D7%A6%D7%A4%D7%95%D7%9F-%D7%9E%D7%A7%D7%93%D7%95%D7%A0%D7%99%D7%94-%D7%94%D7%AA%D7%A9%D7%95%D7%91%D7%94', page: 'תבנית:עושים היסטוריה1' },
  { link: 'https://osimhistoria.com/podcast/%D7%90%D7%99-%D7%A9%D7%95%D7%95%D7%99%D7%95%D7%9F-%D7%91%D7%94%D7%9B%D7%A0%D7%A1%D7%94-%D7%A2%D7%95%D7%A9%D7%99%D7%9D-%D7%97%D7%A9%D7%91%D7%95%D7%9F', page: 'תבנית:עושים היסטוריה1' },
  { link: 'https://osimhistoria.com/podcast/%D7%A2%D7%95%D7%A9%D7%99%D7%9D-%D7%94%D7%99%D7%A1%D7%98%D7%95%D7%A8%D7%99%D7%94-%D7%9E%D7%90%D7%A8%D7%97%D7%AA-%D7%96%D7%99%D7%94%D7%95%D7%99-%D7%93%D7%99%D7%91%D7%95%D7%A8%D7%A2%D7%AA%D7%99%D7%93', page: 'עמי מויאל' },
  { link: 'https://osimhistoria.com/podcast/%D7%94%D7%90%D7%9D-%D7%90%D7%A0%D7%97%D7%A0%D7%95-%D7%97%D7%99%D7%99%D7%9D-%D7%91%D7%A1%D7%99%D7%9E%D7%95%D7%9C%D7%A6%D7%99%D7%94-%D7%94%D7%AA%D7%A9%D7%95%D7%91%D7%94', page: 'השערת הסימולציה' },
  { link: 'https://www.osimhistoria.com/show/osim-tech', page: 'יובל דרור (סוציולוג)' },
  { link: 'https://www.osimhistoria.com/osim-tanach/ep106-abraham-sarah-p1', page: 'אברהם' },
  { link: 'https://www.osimhistoria.com/osim-tanach', page: 'אברהם' }];
// export async function geOsimHistoriaLinksList() {
//   const api = WikiApi();
//   await api.login();
//   const links: string[] = [];
//   const generator1 = api.externalUrl('osimhistoria.com', 'http', '*');

//   for await (const pages of generator1) {
//     pages.
//   }

//   await fs.writeFile('./links.txt', '');
// }

export async function getAllShowEpisodes(showName: string): Promise<string[]> {
  const links: string[] = [];
  let currentPage = 1;
  let pageExists = true;
  while (pageExists) {
    try {
      const res = await fetch(`https://osimhistoria.com/show/${showName}/page/${currentPage}`, {
        signal: AbortSignal.timeout(60 * 1000),
      });
      if (!res.ok) {
        pageExists = false;
      } else {
        const html = await res.text();
        const document = new JSDOM(html);
        const podacastElements = Array.from(document.window.document.querySelectorAll('.podcast').values());
        podacastElements.map((e) => ({
          link: e.querySelector('.elementor-button.elementor-button-link[href]')?.getAttribute('href'),
          text: e.querySelector('h1.elementor-heading-title')?.getAttribute('href'),
        }));
        const pageLinks = Array.from(document.window.document.querySelectorAll('.podcast .elementor-button.elementor-button-link[href]').values())
          .map((e) => e.getAttribute('href'))
          .filter((x: string | null) : x is string => !!x);

        links.push(...pageLinks);
        currentPage += 1;
      }
    } catch (e) {
      console.log(e);
    }
  }
  return links;
}

export function getAllShowLinks(showName: string) {
  const start = `https://www.osimhistoria.com/${showName}/`;
  allLinks.filter((l) => l.link.startsWith(start) && l.link.replace(start, '').length > 1);
}

export default async function osimHistoria() {
  const show = 'osimhistoria';
  //   const links = getAllShowLinks(show);
  const episeds = await getAllShowEpisodes(show);

  await fs.writeFile(`./${show}.json`, JSON.stringify(episeds, null, 2));
}
