extends:
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.eslint.json'
plugins:
  - '@typescript-eslint'
rules:
  "@typescript-eslint/no-unused-vars": error
  jest/prefer-expect-assertions: 0
  jest/no-hooks: 0
  jest/require-hook: 0