name: lint and test
permissions:
  contents: read
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Print GITHUB_REF for code coverage
        run: echo "**--GITHUB_REF=${GITHUB_REF}--**"

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules-v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

      - name: Install modules
        run: npm ci
      - name: Install xmlbot modules
        run: |
          cd xmlbot
          npm ci
          cd ..

      - name: Type check
        run: npm run type-check

      - name: Unit test
        run: npm test

      - name: Run ESLint
        run: npm run lint:test

